spring.mvc.static-path-pattern=/**
spring.resources.static-locations=classpath:/static/

# LOCALE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

# PostgresSQL Database Connection Properties
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/authservice
spring.datasource.username=admin
spring.datasource.password=admin

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Springdoc OpenApi 3.1 & Swagger 3
# springdoc.swagger-ui.path=/docs-chat.html
# springdoc.api-docs.path=/docs-chat
springdoc.packagesToScan=com.Ecommerce.Auth.web.controller

# User-Service REST endpoint
app.user-service.url=http://user-service:8081
