spring.mvc.static-path-pattern=/**
spring.resources.static-locations=classpath:/static/

# LOCALE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

server.port=8081

# PostgresSQL Database Connection Properties
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/userservice
spring.datasource.username=admin
spring.datasource.password=admin

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Springdoc OpenApi 3.1 & Swagger 3
springdoc.packagesToScan=com.Ecommerce.User.web.controller

